### PR TITLE
Fix build on Hyprland 0.55.2 (render pass API change)

### PR DESCRIPTION
**Pull request by vadika**
## What

Fixes the plugin failing to build against **Hyprland 0.55.2**.

## Why

In 0.55.2, `CRenderPass::m_passElements` changed type:

\`\`\`cpp
// render/pass/Pass.hpp
std::vector<UP<SPassElementData>> m_passElements;   // was vector<SPassElementData>
\`\`\`

So the \`std::erase_if\` lambda in \`HTLayoutBase::post_render()\` now receives a
\`UP<SPassElementData>\` (unique-pointer) rather than the struct by value, and the
existing \`e.element\` no longer compiles:

\`\`\`
src/layout/layout_base.cpp:87:22: error: 'const class Hyprutils::Memory::CUniquePointer<Render::CRenderPass::SPassElementData>' has no member named 'element'
\`\`\`

## Change

- \`e.element->passName()\` → \`e->element->passName()\` (dereference the UP first).
- Uncomment the \`v0.55.2\` commit pin in \`hyprpm.toml\` so hyprpm accepts the plugin on 0.55.2.

## Testing

Builds clean and loads live on Hyprland 0.55.2 (commit \`39d7e209\`); \`hyprtasking:toggle\` works.

### CODE REVIEW

**Comment by raybbian** [comment]
Hi! Was this a fix for v0.55.2 only? If so, you need to ensure that you overwrite the changes with a new commit so that more recent versions continue to work.
