### ISSUE TITLE
Fails to build on 0.54.2

### ISSUE THREAD

**Issue by hkcowboy** [raybbian/hyprtasking#104]
Hello, I am on hyprland 0.54.2 and trying to add hyprtasking.  Have uploaded hyprppm add log showing error.  I also tried the steps outlined in the 0.54.0 PR but it did not work, including adding the commit pin.  Thank you in advance.

[hyprtasking.log](https://github.com/user-attachments/files/26159006/hyprtasking.log)

**Comment by yerlotic** [comment]
I can't reproduce the issue.
It seems that you have several versions of hyprland source files, so they conflict (`redefinition of ...`)
Try installing hyprland only from the package manager or only from the git repo, you might have installed it both ways so now it is not working

Try rebooting or reinstalling hyprland.

Here is my log:

```log
~ $ hyprpm add https://github.com/yerlotic/hyprtasking
✔ Headers up to date.
✔ adding a new plugin repository from https://github.com/yerlotic/hyprtasking
  MAKE SURE that you trust the authors. DO NOT install random plugins without verifying the code and author.
  Are you sure? [Y/n] 

→ Cloning https://github.com/yerlotic/hyprtasking
✔ cloned
✔ found hyprpm manifest
✔ parsed manifest, found 1 plugins:
→ hyprtasking by raybbian version 
→ Manifest has 18 pins, checking
✔ Hyprland headers OK
→ Building hyprtasking
✔ built hyprtasking into build/libhyprtasking.so
✔ all plugins built
✔ installed repository
✔ you can now enable the plugin(s) with hyprpm enable
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5 / 5  Done!
~ $ hyprpm enable hyprtasking
✔ Enabled hyprtasking
✔ Ensuring plugin load state
✔ Loaded dynamic-cursors
✔ Loaded hyprtasking
✔ Plugin load state ensured
~ $ hyprland --version
Hyprland 0.54.2 built from branch v0.54.2 at commit 59f9f2688ac508a0584d1462151195a6c4992f99 clean (version: bump to 0.54.2).
Date: Tue Mar 10 13:26:58 2026
Tag: v0.54.2, commits: 6998

Libraries:
Hyprgraphics: built against 0.5.0, system has 0.5.0
Hyprutils: built against 0.11.0, system has 0.11.1
Hyprcursor: built against 0.1.13, system has 0.1.13
Hyprlang: built against 0.6.8, system has 0.6.8
Aquamarine: built against 0.10.0, system has 0.10.0

Version ABI string: 59f9f2688ac508a0584d1462151195a6c4992f99_aq_0.10_hu_0.11_hg_0.5_hc_0.1_hlg_0.6
no flags were set
```

**Comment by hkcowboy** [comment]
seems like hyprland 0.54.2 build by debian has some issue:
❯ hyprpm update -v
[sudo] password for user:
[v] parsed commit unknown at branch unknown on unknown, commits 0, nix: false
[v] parsed commit unknown at branch unknown on unknown, commits 0, nix: false

**Comment by GalaxyXYZ888** [comment]
For me it builds but the gestures and the clicks are broken. 
"bind = $mainMod, g, hyprtasking:toggle, cursor" this works but the gestures with the trackpad to open and close doesn't work, and also the clicks dont work i have changed nothing in the config since the update.

**Comment by yerlotic** [comment]
@GalaxyXYZ888 
Were trackpad gestures working before the update?
Are you talking about trackpad or touchpad gestures?
What was the working version?
Maybe your driver is broken if clicks aren't working. Did you try to click with a mouse?

**Comment by GalaxyXYZ888** [comment]
> [@GalaxyXYZ888](https://github.com/GalaxyXYZ888) Were trackpad gestures working before the update? Are you talking about trackpad or touchpad gestures? What was the working version? Maybe your driver is broken if clicks aren't working. Did you try to click with a mouse?

1 - Yes the gestures are working fine on 0.54.1 (i rolled back with a snapshot)
2 - Well now you got me i don't really know the difference xd. I am talking about opening with 3 fingers up and closing with 3 fingers down for example. My laptop is a DELL XPS15 9510 if that helps.
3 - Latest build on 0.54.1 
4 - Yeah the update was massive so it could be, but i tried indeed click with a mouse that i usually used and got the same problem. 

Since people here have tested it maybe it was some CachyOS problem etc i updated everything not only Hyprland.

**Comment by yerlotic** [comment]
> 2 - I am talking about opening with 3 fingers up and closing with 3 fingers down for example. 

So you have this in your hyprtasking configuration, right?

```
gestures {
  enabled = true
  open_fingers = 3
}
```

> 4 - Yeah the update was massive so it could be, but i tried indeed click with a mouse that i usually used and got the same problem.

Not sure what you mean here. [Here](https://github.com/hyprwm/Hyprland/releases/tag/v0.54.2) is 0.54.2 update. Very few things were actually backported. 

Can you click with a mouse (RMB and LMB) on a workspace so the overview closes? Does it work on 0.54.1? Does it work on 0.54.2?

**Comment by GalaxyXYZ888** [comment]
> > 2 - I am talking about opening with 3 fingers up and closing with 3 fingers down for example.
> 
> So you have this in your hyprtasking configuration, right?
> 
> ```
> gestures {
>   enabled = true
>   open_fingers = 3
> }
> ```
> 
> > 4 - Yeah the update was massive so it could be, but i tried indeed click with a mouse that i usually used and got the same problem.
> 
> Not sure what you mean here. [Here](https://github.com/hyprwm/Hyprland/releases/tag/v0.54.2) is 0.54.2 update. Very few things were actually backported.
> 
> Can you click with a mouse (RMB and LMB) on a workspace so the overview closes? Does it work on 0.54.1? Does it work on 0.54.2?



Yes i have those gesture settings. Everything is working fine in 0.54.1. 

Yeah what i meant is that i Syu so i updated all the packages maybe something was interfering idk. 

"Can you click with a mouse (RMB and LMB) on a workspace so the overview closes? Does it work on 0.54.1? Does it work on 0.54.2?" No, for me in 0.54.2 they didnt work, neither of them, but in 0.54.1 they work. 

I rolled back because i also had other dependency broken in another program but i can try again and try to get some logs or any information, i wouldn't know where to start looking tho. Only opening and closing with "bind = $mainMod, g, hyprtasking:toggle, cursor" was working for me, everything else clicks, gestures etc were broken.

**Comment by yerlotic** [comment]
Okay, the issue actually exists. 
And it's an issue in hyprtasking
But it was working on 0.54.2 for me, then with hyprland v0.54.2-2 (and maybe some other packages) it stopped working.
I'll try to fix this issues

**Comment by yerlotic** [comment]
Okay, IPointer::SSwipeUpdateEvent.fingers reports 32767 fingers. It's a bug in Hyprland

Edit: reported it here: https://github.com/hyprwm/Hyprland/discussions/13867

**Comment by GalaxyXYZ888** [comment]
Ok good i was afraid i was wasting your time with a broken config in something on my end xd 

> Okay, IPointer::SSwipeUpdateEvent.fingers reports 32767 fingers. It's a bug in Hyprland
> 
> Edit: reported it here: [hyprwm/Hyprland#13867](https://github.com/hyprwm/Hyprland/discussions/13867)

How does that make it so clicks and mouse clicks also dont work ? Did that also happened to you?

**Comment by yerlotic** [comment]
> How does that make it so clicks and mouse clicks also dont work ? Did that also happened to you?

Yes, this happened to me as well. The clicks were passed to the active workspace for some reason. But I didn't have time to investigate further

**Comment by yerlotic** [comment]
@GalaxyXYZ888, it is fixed in v0.54.3. I think it was an issue with arch packaging

**Comment by GalaxyXYZ888** [comment]
Confirmed works perfectly now!

**Comment by hkcowboy** [comment]
Hi, I had to wait for debian to push a fix and then I had to purge cache then it worked.  Since others seem to be using this issue too, please close this issue when y'all want.

Thank you for your help!

**Comment by yerlotic** [comment]
Everything seems to be resolved now, so you can close the issue (I don't have the rights on this repo)
